### ISSUE TITLE
[Bug] «UnicodeEncodeError: 'charmap' codec can't encode characters in position 87-89»

### ISSUE THREAD

**Issue by Kristinita** [yrammos/SublimeLog#2]
### Summary

I get stack trace, when I run `command log_console_output`.
### Expected behavior

No stack traces.
### Actual behavior

``` python
key evt: control+alt+c
command: log_console_output
<= <= <= Console logging deactivated (E:/Sublime Text 3/Data/.subl.log). Timestamp: 02 îêò 2016, 14:50:17.Traceback (most recent call last):
  File "E:\Sublime Text 3\sublime_plugin.py", line 782, in run_
    return self.run()
  File "SublimeLog in E:\Sublime Text 3\Data\Installed Packages\SublimeLog.sublime-package", line 58, in run
  File "SublimeLog in E:\Sublime Text 3\Data\Installed Packages\SublimeLog.sublime-package", line 66, in write
  File "./python3.3/encodings/cp1251.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 87-89: character maps to <undefined>
```
### Steps to reproduce

I press <kbd>Ctrl+Alt+C</kbd> → I get stack trace.
### Additional information

Part of my `User\Preferences.sublime-settings` file:

```
"fallback_encoding": "Cyrillic (Windows 1251)",
```

My `User\SublimeLog.sublime-settings` file:

```
{
    "logfile":  "E:\\Sublime Text 3\\Data\\.subl.log"
}
```

When I open `.subl.log` file I saw in console:

```
reloading /E/Sublime Text 3/Data/.subl.log
unable to auto detect encoding for E:\Sublime Text 3\Data\.subl.log, using fallback encoding Cyrillic (Windows 1251)
```
### Environment

**Operating system and version:**
Windows 10.0.14393
**Sublime Text:**
Build 3126

Thanks.

**Comment by yrammos** [comment]
Thanks for reporting and apologies for the inconvenience. Unfortunately I won't be able to work on this for a couple of weeks at least as I'm traveling without the laptop. Thank you for your patience.

**Comment by Kristinita** [comment]
@yrammos , actually. Thanks.

**Comment by yrammos** [comment]
@Kristinita do you get this message only when you deactivate the logger, or when you activate it, as well? I guess in both cases, but would appreciate a confirmation as I don't have a Windows machine and need to debug this as a "thought experiment" of sorts. Thank you.

**Comment by yrammos** [comment]
@Kristinita the issue should now be fixed. Please test on your windows set up and confirm, as I have no Windows machines at my disposal.

**Comment by Kristinita** [comment]
Thanks, now I can get no stack trace!
