### ISSUE TITLE
[Feature request] Not erased previous logs

### ISSUE THREAD

**Issue by Kristinita** [yrammos/SublimeLog#3]
### 1. Request

> The log is erased and recreated each time Sublime Text is launched.

It would be nice, if logs will not erase.

### 2. Justification

+ sometimes I need to see old logs,
+ to compare the old and the new log I need have old logs, but now old logs erased.

### 3. Desirable behavior

Will be created new folder SublimeLog → in start every new session in SublimeLog folder will be created new log file in `$date$time.log` format, for example, `2016-02-12-15:53:14.log`. After restart Sublime Text `2016-02-12-15:53:14.log` will be saved and will be created new file, for example, `2016-02-12-16:00:00.log`. `2016-02-12-15:53:14.log` already not will be delete or rewrite.

Thanks.

**Comment by yrammos** [comment]
@Kristinita thank you for your suggestion, of which I recognize the merits. That said, as the project subtitle suggests, SublimeLog is intended to be a "bare-bones" logger, and I would prefer to keep its feature set absolutely minimal. There are several ways in which you could get the result you describe via the terminal, the most straightforward of which is to use `multitail` (on all major Unix platforms, including macOS, as well as Windows via Cygwin):

`multitail .subl.log`

This short command will maintain the entire history of logs even across restarts of the app.

You may find `multitail` at https://www.vanheusden.com/multitail/ (the Mac version is also available via Homebrew).

I hope this helps.

**Comment by Kristinita** [comment]
@yrammos , I hope, you ever change your mind and add function.

Thanks.
